### ISSUE TITLE
default config + missing notifications

### ISSUE THREAD

**Issue by laur89** [ram-on/imgurbash2#6]
Hi again,
I have some comments re. f7e81fd3d3e558e9475508413d171428134c1c1d

1) getting rid of default config definitions, and replacing them by manual config file initialisation (@ `# if the configuration file does not exist, then initialize it`) is a horrible idea; users who already have a config file but are missing certain elements (say `COPY_URL_TO_CLIP`) would now be tracking unexpected defaults: `COPY_URL_TO_CLIP == true` and similar checks would fail for them;
1) I don't agree with the reasoning for removing notifications:
> Removed popup notifications as they do not make any sense to have in 
the first place

Imho feedback is good; otherwise how do we know:
a) whether command failed or succeeded
b) has the command returned or is it still running?

Any chance you'd consider reverting these 2 features?

**Comment by ram-on** [comment]
Hello.  Must have missed this.

1. I doubt more configs will be added.
2. Sorry I don't agree with having desktop notifications whenever an image is uploaded, especially when uploading multiple images = multiple notifications.  This is especially true since an image takes less than a second to upload.
